In [ ]:
!pip install --upgrade wandb

     |████████████████████████████████| 2.0MB 5.4MB/s 
     |████████████████████████████████| 102kB 9.2MB/s 
     |████████████████████████████████| 133kB 40.4MB/s 
     |████████████████████████████████| 163kB 30.5MB/s 
     |████████████████████████████████| 71kB 7.4MB/s 
  Created wheel for subprocess32: filename=subprocess32-3.5.4-cp37-none-any.whl size=6489 sha256=990e655246aaa94b605a766efd7adfbe479a82bb9d1325f7ae7116579a59647e
  Stored in directory: /root/.cache/pip/wheels/68/39/1a/5e402bdfdf004af1786c8b853fd92f8c4a04f22aad179654d1
  Created wheel for pathtools: filename=pathtools-0.1.2-cp37-none-any.whl size=8786 sha256=635285a01728fb93f7fa3b89870f3c5dead25da1d1b5466c782168856d8a8622
  Stored in directory: /root/.cache/pip/wheels/0b/04/79/c3b0c3a0266a3cb4376da31e5bfe8bba0c489246968a68e843
Successfully built subprocess32 pathtools


In [ ]:
!wandb login bc083bd9200d3ae33f03b753f8b734bfe42e9abf

wandb: Appending key for api.wandb.ai to your netrc file: /root/.netrc


In [10]:
from keras.datasets import fashion_mnist
import numpy as np



In [3]:
def plot_images():
  plottedClass =  [False for i in range(10)] 
  images=[]
  classes=[]
  for i in range(100):
      if  plottedClass[y_train[i]]==False:
        images.append(X_train[i])
        classes.append(labels[y_train[i]])
        plottedClass[y_train[i]]=True
  wandb.log({"example": [wandb.Image(img,caption=label) for img,label in zip(images,classes)]})

In [83]:
class Activation_Sigmoid:
  def forward(self,inputs):
    self.output=1/(1 + np.exp(-inputs))
  def gradient(self,outp):
    self.deltaoutput=outp * (1 - outp)
  def printActivationLayerProperties(self):
    print("Activation Layer Properties")
    print("h",self.output.shape)
    print("deltah",self.deltaoutput.shape)

In [11]:
class CrossEntropy():
    def __init__(self, y_true, y_pred):
        self.y_true = y_true
        self.y_pred = y_pred
    def calculateLoss(self):
        return -np.sum(self.y_true * np.log(self.y_pred))

    def grad(self):
        return -(self.y_true/(self.y_pred + 1e-9))

In [ ]:
import numpy as np
a=np.random.randn(10)
sigmoid=Activation_Sigmoid();
sigmoid.forward(a)
print(sigmoid.output)

In [6]:
#Testing sigmoid activation fuction
import numpy as np
a=np.random.randn(10)
sigmoid=Activation_Sigmoid();
sigmoid.forward(a)
print(sigmoid.output)
sigmoid.gradient(sigmoid.output)
print(sigmoid.deltaoutput.shape)

[0.64128652 0.58864175 0.29268632 0.75371013 0.44758574 0.51330867
 0.47557225 0.54406288 0.74031678 0.29963205]
(10,)


In [12]:
class Activation_Softmax:
  def forward(self,inputs):
    numerator_values=np.exp(inputs-np.max(inputs))
    probabilites=numerator_values/np.sum(numerator_values)
    self.output=probabilites


In [89]:
import numpy as np
a=np.random.randn(10)
softmax=Activation_Softmax();
softmax.forward(a)
print(sum(softmax.output))

2.906169778958145
1.0


In [143]:
import numpy as np
class Layer:
  def __init__(self,n_inputs,n_neurons):
    self.weights=0.10*np.random.randn(n_inputs,n_neurons)
    self.biases=np.zeros((1,n_neurons))
    self.deltaWeights= np.zeros((n_inputs,n_neurons))
    self.deltaBiases= np.zeros((1,n_neurons))
    self.deltaOutput=np.zeros((1,n_neurons))
  def getWeights(self):
    return self.weights
  def getBiases(self):
    return self.biases
  def forward(self,inputs):
    self.output= np.dot(inputs,self.weights)+self.biases
  def delta(self,delWeights,delbiases,deloutput):
    self.deltaWeights= delWeights
    self.deltaBiases= delbiases
    self.deltaOutput = deloutput
  def update_StochsticGradientDescent(self,eta):
    print("updateWeights")
    self.weights= self.weights- eta*self.deltaWeights
    self.biases=self.biases-eta*self.deltaBiases
  def printLayerProperties(self):
    print("weights ",self.weights.shape)
    print("biases ",self.biases.shape)
    print("ouput-a",self.output.shape)
    print("deltaWeights",self.deltaWeights.shape)
    print("deltaBiases",self.deltaBiases.shape)
    print("delta-a",self.deltaOutput.shape)

In [112]:
def feedForward(NoOfLayers,NoOfOutputClasses,index):
  #feed forward
  print("feedForward")
  Layers[0].forward(X_train[index:index+1])
  HiddenLayersActivation[0].forward(Layers[0].output)
  print("HiddenLayer 1")
  for j in range(NoOfLayers-2):
    print("HiddenLayer",j+2)
    Layers[j+1].forward(HiddenLayersActivation[j].output)
    HiddenLayersActivation[j+1].forward(Layers[j+1].output)
  print("OutputLayer")
  Layers[NoOfLayers-1].forward(HiddenLayersActivation[NoOfLayers-2].output)
  opActivation.forward(Layers[NoOfLayers-1].output)
  print(y_train[index:index+1])

In [133]:
import numpy as np

def predict(NoOfLayers,NoOfOutputClasses,index):
  Layers[0].forward(X_test[index:index+1])
  HiddenLayersActivation[0].forward(Layers[0].output)
  for j in range(NoOfLayers-2):
    Layers[j+1].forward(HiddenLayersActivation[j].output)
    HiddenLayersActivation[j+1].forward(Layers[j+1].output)
  Layers[NoOfLayers-1].forward(HiddenLayersActivation[NoOfLayers-2].output)
  opActivation.forward(Layers[NoOfLayers-1].output)
  print(np.argmax(opActivation.output,axis=1))
  print(y_test[index])

In [ ]:
# def BackPropogation(NoOfLayers,index):
#   deltaOutput=-(y_train[index:index+1]-opActivation.output)
#   deltaOutput=deltaOutput.T
#   print("deltaAL: ", deltaOutput.shape)
#   print("BackPropogate")
#   for k in range(NoOfLayers-1,0,-1):
#     print("HiddenLayer: ",k)
#     deltaWeights=np.dot(deltaOutput,HiddenLayersActivation[k-1].output)
#     print("deltaWeights ",deltaWeights.shape)
#     deltaBiases=deltaOutput
#     print("deltaBiases: ",deltaBiases.shape)
#     Layers[k].delta(deltaWeights,deltaBiases,deltaOutput)
#     deltaActivationOutput=np.dot(Layers[k].weights,deltaOutput)
#     print("deltaH",k-1)
#     print(deltaActivationOutput.shape)
#     HiddenLayersActivation[k-1].gradient(Layers[k-1].output)
#     print("gdash",HiddenLayersActivation[k-1].deltaoutput.T.shape)
#     deltaOutput=deltaActivationOutput*(HiddenLayersActivation[k-1].deltaoutput.T)
#     print("deltaA",k-1)
#     print(deltaOutput.shape)
#   deltaWeights=np.dot(deltaOutput,X_train[index:index+1])
#   print("Layer",0)
#   print(deltaWeights.shape)
#   deltaBiases=deltaOutput
#   print(deltaBiases.shape)

In [109]:
#Backward Propogation
def BackPropogation(NoOfLayers,index):
  deltaOutput=-(y_train[index:index+1].T-opActivation.output.T)
  print("BackPropogate")
  for k in range(NoOfLayers-1,0,-1):
    print("HiddenLayer: ",k)
    deltaWeights=np.dot(deltaOutput,HiddenLayersActivation[k-1].output)
    deltaBiases=deltaOutput.T
    Layers[k].delta(deltaWeights,deltaBiases,deltaOutput.T)
    deltaActivationOutput=np.dot(Layers[k].weights,deltaOutput)
    HiddenLayersActivation[k-1].gradient(Layers[k-1].output)
    deltaOutput=deltaActivationOutput*(HiddenLayersActivation[k-1].deltaoutput.T)
  deltaWeights=np.dot(deltaOutput,X_train[index:index+1])
  deltaBiases=deltaOutput


In [45]:
y_pred=[0.22963919,0.000663 ,  0.01329421, 0.46463921, 0.0198872 , 0.08159455,
 0.04012039, 0.02962026, 0.03042951, 0.09011247]
y_true=[1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
np.log(y_pred)
#-np.sum(y_true * np.log(y_pred))

array([-1.47124594, -7.31873557, -4.32042668, -0.76649407, -3.91767897,
       -2.50599281, -3.2158706 , -3.51929669, -3.49234242, -2.40669672])

In [11]:
def preprocessing():
  


In [144]:
#import wandb
#wandb.init(project="fashon_mnist", entity="manideepladi")
# Log metrics with wandb
from keras.datasets import fashion_mnist
import numpy as np

import random

(X_train, y_train), (X_test, y_test) = fashion_mnist.load_data()
labels=["T-shirt/top","Trouser","Pullover","Dress","Coat",
        "Sandal","Shirt","Sneaker","Bag","Ankle boot"]
#plot_images()

#Preprocessing
X_train = X_train / 255.0
X_test = X_test / 255.0
# print(X_train.shape)
X_train = np.reshape(X_train, (X_train.shape[0],28*28))
X_test = np.reshape(X_test, (X_test.shape[0],28*28))
# print(X_train.shape)
# print(y_train.shape)
# print(y_test.shape)
#converting output vectors to one-hot encoders
y_train= np.eye(len(labels))[y_train]
y_test= np.eye(len(labels))[y_test]
# print(y_train.shape)
# print(y_test.shape)

NoOfLayers=2
Layers=[]
HiddenLayersActivation=[]
for i in range(NoOfLayers):
  if i==NoOfLayers-1:
    Layers.append(Layer(784,10))
  Layers.append(Layer(784,784))
  HiddenLayersActivation.append(Activation_Sigmoid())

opActivation=Activation_Softmax()
for i in range(100,115,1):
  predict(NoOfLayers,10,i)
  print("------------")
for i in range(10):
  index=random.randint(0,59999)
  #print(index)
  feedForward(NoOfLayers,10,index)
  crossEntropyLoss=CrossEntropy(y_train[index:index+1],opActivation.output)
  print(crossEntropyLoss.calculateLoss())
  for j in range(NoOfLayers-1):
    #print("Layer-------------- ",j)
    #Layers[j].printLayerProperties()
    Layers[j].update_StochsticGradientDescent(0.001)
  BackPropogation(NoOfLayers,index)
  print("---------------------------------------------------")
for i in range(100,115,1):

  predict(NoOfLayers,10,i)
  print("------------")
# Save model to wandb


[8]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
------------
[8]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
------------
[8]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
------------
[8]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
------------
[8]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
------------
[7]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
------------
[8]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
------------
[7]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
------------
[7]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
------------
[8]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
------------
[8]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
------------
[8]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
------------
[8]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
------------
[8]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
------------
[7]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
------------
feedForward
HiddenLayer 1
OutputLayer
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
5.393111672398663
updateWeights
BackPropogate
HiddenLayer:  1
---------------------------------------------------
feedForward
HiddenLayer 1
OutputLayer
[[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]
4.18750